services:
  db:
    image: postgres:17-alpine
    container_name: appointments-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - appointments-db-data:/var/lib/postgresql/data
    networks:
      - appointments-network

  app:
    image: appointments-api
    container_name: appointments-api
    build:
      context: .
      dockerfile: src/Appointments.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};User ID=${DB_USER};Password=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - appointments-network

volumes:
  appointments-db-data:

networks:
  appointments-network:
